// this file exists to contain no-no words that cause Github Copilot to refuse to function

export const focusTags: string[] = [
  'armpit focus',
  'ass focus',
  'back focus',
  'breast focus',
  'eye focus',
  'foot focus',
  'hand focus',
  'hip focus',
  'navel focus',
  'pectoral focus',
  'thigh focus',
]

export const faceTagsFailsList: string[] = [
  ';\\)',
  ':>',
  '+_-',
  '>_@',
  'aroused',
  '0w0',
  'd:',
  '3:',
  'essex face',
  'excalibur face',
  'doyagao',
  'face of the people who sank all their money into the fx',
  'uwu',
  'x3',
]

export const faceTagsList: string[] = [
  'angry',
  'anger vein',
  'annoyed',
  'clenched teeth',
  'scowl',
  'blush',
  'blush stickers',
  'embarrassed',
  'full-face blush',
  'nose blush',
  'bored',
  'closed eyes',
  'confused',
  'crazy',
  'despair',
  'determined',
  'disappointed',
  'disdain',
  'disgust',
  'drunk',
  'envy',
  'excited',
  'exhausted',
  'expressionless',
  'facepalm',
  'flustered',
  'frustrated',
  'furrowed brow',
  'grimace',
  'guilt',
  'happy',
  'kubrick stare',
  'lonely',
  'nervous',
  'nosebleed',
  'one eye closed',
  'round mouth',
  'open mouth',
  'parted lips',
  'pain',
  'pout',
  'raised eyebrow',
  'raised inner eyebrows',
  'rape face',
  'rolling eyes',
  'sad',
  'depressed',
  'frown',
  'gloom \\(expression\\)',
  'tears',
  'scared',
  'panicking',
  'worried',
  'serious',
  'sigh',
  'sleepy',
  'sulking',
  'surprised',
  'thinking',
  'pensive',
  'v-shaped eyebrows',
  'wince',
  'afterglow',
  'ahegao',
  'fucked silly',
  'in heat',
  'naughty face',
  'seductive smile',
  'torogao',
  'crazy smile',
  'evil smile',
  'fingersmile',
  'forced smile',
  'glasgow smile',
  'grin',
  'evil grin',
  'light smile',
  'sad smile',
  'smile',
  'stifled laugh',
  'smirk',
  'smug',
  ':d',
  ';d',
  'xd',
  ':3',
  ';3',
  ':p',
  ';p',
  ':q',
  ';q',
  '>:\\)',
  '>:\\(',
  ':t',
  ':i',
  ':/',
  ':|',
  'x mouth',
  ':c',
  'c:',
  ':<',
  ';<',
  'diamond mouth',
  ':>=',
  ':o',
  ';o',
  'o3o',
  '>3<',
  'o_o',
  '0_0',
  '|_|',
  '._.',
  'solid circle eyes',
  'heart-shaped eyes',
  '^_^',
  '\\\\\\(^o^\\)/',
  '^q^',
  '>_<',
  '>o<',
  '@_@',
  '+_+',
  '=_=',
  '=^=',
  '=v=',
  '<o>_<o>',
  '<|>_<|>',
  'angry dog noises',
  'awesome face',
  'gyate gyate',
  'henohenomoheji',
  'nonowa',
  'smiley face',
  'troll face',
  'uso da',
]
