// this file exists to contain no-no words that cause Github Copilot to refuse to function

interface Tag {
  name: string
  positivePromptOverride?: string
  negativePromptOverride?: string
}

const noOverride = (tag: string): Tag => ({ name: tag })

export const focusTags: Tag[] = [
  'armpit focus',
  'ass focus',
  'back focus',
  'breast focus',
  'foot focus',
  'hip focus',
  'thigh focus',
]
  .map(noOverride)
  .concat([
    {
      name: 'pectoral focus',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, 1girl, solo, medium breasts, t-shirt,  (pectoral focus:1.1),',
    },
    {
      name: 'hand focus',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, 1girl, solo,  (hand focus:1.1)',
    },
    {
      name: 'navel focus',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, 1girl, solo,  (navel focus:1.1)',
    },
    {
      name: 'eye focus',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, 1girl, solo,  (eye focus:1.1),',
    },
  ])

export const faceTagsFailsList: Tag[] = [
  ':>',
  '+_-',
  '>_@',
  'aroused',
  '0w0',
  'd:',
  '3:',
  'essex face',
  'excalibur face',
  'doyagao',
  'face of the people who sank all their money into the fx',
  'uwu',
  'x3',
].map(noOverride)

export const faceTagsList: Tag[] = [
  'angry',
  ';\\)',
  'anger vein',
  'annoyed',
  'clenched teeth',
  'scowl',
  'blush',
  'blush stickers',
  'embarrassed',
  'full-face blush',
  'nose blush',
  'bored',
  'closed eyes',
  'confused',
  'crazy',
  'despair',
  'determined',
  'disappointed',
  'disdain',
  'disgust',
  'drunk',
  'envy',
  'excited',
  'exhausted',
  'expressionless',
  'facepalm',
  'flustered',
  'frustrated',
  'furrowed brow',
  'grimace',
  'guilt',
  'happy',
  'kubrick stare',
  'lonely',
  'nervous',
  'nosebleed',
  'one eye closed',
  'round mouth',
  'open mouth',
  'parted lips',
  'pain',
  'pout',
  'raised eyebrow',
  'raised inner eyebrows',
  'rape face',
  'rolling eyes',
  'sad',
  'depressed',
  'frown',
  'gloom \\(expression\\)',
  'tears',
  'scared',
  'panicking',
  'worried',
  'serious',
  'sigh',
  'sleepy',
  'sulking',
  'surprised',
  'thinking',
  'pensive',
  'v-shaped eyebrows',
  'wince',
  'afterglow',
  'ahegao',
  'fucked silly',
  'in heat',
  'naughty face',
  'seductive smile',
  'torogao',
  'crazy smile',
  'evil smile',
  'fingersmile',
  'forced smile',
  'glasgow smile',
  'grin',
  'evil grin',
  'light smile',
  'sad smile',
  'smile',
  'stifled laugh',
  'smirk',
  'smug',
  ':d',
  ';d',
  ':3',
  ';3',
  ':p',
  ';p',
  ':q',
  ';q',
  '>:\\)',
  '>:\\(',
  ':t',
  ':i',
  ':/',
  ':|',
  'x mouth',
  ':c',
  'c:',
  ':<',
  ';<',
  'diamond mouth',
  ':>=',
  ':o',
  ';o',
  'o3o',
  '>3<',
  'o_o',
  '0_0',
  '|_|',
  '._.',
  '^_^',
  '\\\\\\(^o^\\)/',
  '^q^',
  '>_<',
  '>o<',
  '@_@',
  '+_+',
  '=_=',
  '=^=',
  '=v=',
  '<o>_<o>',
  '<|>_<|>',
  'angry dog noises',
  'awesome face',
  'gyate gyate',
  'henohenomoheji',
  'nonowa',
  'smiley face',
  'uso da',
]
  .map(noOverride)
  .concat([
    {
      name: 'xd',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, official art, 1girl, solo, white shirt, bob cut, black hair, upper body, straight-on, looking at viewer, simple background, laughing, (xd:1.1),',
    },
    {
      name: 'solid circle eyes',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, official art, 1girl, solo, white shirt, bob cut, black hair, upper body, straight-on, looking at viewer, simple background, (solid circle eyes:1),',
    },
    {
      name: 'heart-shaped eyes',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, official art, 1girl, solo, white shirt, bob cut, black hair, upper body, straight-on, looking at viewer, simple background, open mouth, (heart-shaped eyes:1),',
    },
    {
      name: 'troll face',
      positivePromptOverride:
        'masterpiece, best quality, amazing quality, official art, 1girl, solo, white shirt, bob cut, black hair, upper body, straight-on, looking at viewer, simple background, smile, (troll face:1.1),',
    },
  ])
